# Generated by Django 4.1.5 on 2023-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_data', models.JSONField(default={})),
                ('video_id', models.CharField(max_length=200)),
                ('search_tag', models.CharField(choices=[('HOCKEY', 'hockey'), ('FOOTBALL', 'football'), ('ECONOMY', 'economy'), ('INDIA', 'india')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
